baseURL = 'https://yennj12.js.org/yennj12_blog_V4'
languageCode = 'en-us'
title = 'YennJ12 Engineering Blog'
theme = 'uber-style'
buildFuture = true

[params]
  description = 'Engineering insights, architecture deep dives, and technical solutions'
  author = 'YennJ12 Engineering Team'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    codeFences = true
    lineNumbersInTable = false
    noClasses = false

[markup.goldmark.parser]
    attribute = true

[markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Engineering'
    url = '/categories/engineering/'
    weight = 20
  [[menu.main]]
    name = 'Architecture'
    url = '/categories/architecture/'
    weight = 30
  [[menu.main]]
    name = 'Data'
    url = '/categories/data/'
    weight = 40
  [[menu.main]]
    name = 'All Posts'
    url = '/posts-list/'
    weight = 45
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[related]
  includeNewer = false
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10
